# SPDX-FileCopyrightText: 2024 2024 Quantum Application Lab
#
# SPDX-License-Identifier: Apache-2.0

version: 2
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev
